title: Coolt race - 8 feb 2022
footer: Resultat genererat av Team 05
resultFile: ./output/resultat.txt
nameFile: ./input/namnfil.txt
sorting: true
type: marathon
marathon:
  minimumTime: '00:05:01'
  startTimesFile: ./input/starttider.txt
  goalTimesFile: ./input/maltider1.txt
lap:
  minimumTime: '00:05:00'
  massStart: false
  timeForMassStart: '13:00:00'
  startTimesFile: ./input/starttider.txt
  goalTimesFiles:
    - ./input/maltider.txt
  raceEndTime: '14:00:00'
port: 4000
